### ISSUE TITLE
Builds seem to break and there is no Docker Hub image signature available

### ISSUE THREAD

**Issue by interN3rd** [renovatebot/docker-renovate-full#1475]
Hi,

I am using Cosign to verify Docker images. The command I run is for example `COSIGN_EXPERIMENTAL=1 cosign verify -o json renovate/renovate:34.159.1@sha256:2e8c964a0123f9fe24cde42a5c315e174cce583074e3bb66bf5a8806778a268f`. But this returns with `Error: no matching signatures`. Since I can't (and don't want to) skip the image validation, I am not able to update Renovate at the moment.

And looking at the GitHub Actions, the builds seem to be broken: https://github.com/renovatebot/docker-renovate-full/actions/runs/4365106959 and https://github.com/renovatebot/docker-renovate-full/actions/runs/4365106958

What can be done here? Do I need to change my command that I run or my configuration?

Kind regards

**Comment by viceice** [comment]
I'll look into it soon

**Comment by viceice** [comment]
Our internal tool action release was broken, so the action binaries stayed at `v1.14.14`[^1] 😕
We need to wait for next release and bubble through.
Then we should get new images again.

[^1]: https://github.com/containerbase/internal-tools

**Comment by interN3rd** [comment]
Sounds good to me :) At the moment I'm going with Renovate 34.157.0 and it works fine. Builds of versions 34.157.1 and newer did break and I couldn't figure out why. Thank you for clearing it up and especially for providing fixes that fast. Thanks

**Comment by viceice** [comment]
#1478 should cause a digest change, so latest 10 renovate versions will be rebuild

**Comment by interN3rd** [comment]
Can confirm that everything runs as smooth as before now. Thank you! Great effort and fixed rapidly fast
