### ISSUE TITLE
Default to `binarySource=global` as breaking change in next major release?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/docker-renovate-full#1599]
Copy/pasting a comment from @rarkins on a PR: [^quote]

> Maybe the full image should default to `binarySource=global` as a breaking change in a next major release?

I'll let the maintainers decide if this is a good idea. 😉 

[^quote]: https://github.com/renovatebot/renovate/pull/21222#discussion_r1155245218

**Comment by viceice** [comment]
the current mode is install, so if renovate needs a tool which is preinstalled, but in an older version, then the never version gets installed on the fly.

also if an older version is requested by a project it will be installed on the fly.

**Comment by rarkins** [comment]
I'm thinking that the main use case for the "full" image is people who don't want to install on the fly. So then we could default slim to install but full to global.

**Comment by rarkins** [comment]
Also we could switch which type of image is default for `renovate/renovate`

**Comment by rarkins** [comment]
I have observed a _lot_ of people surprised that the image needs to reach out to e.g. github.com to look up tool releases. Defaulting to slim/install seems like a good compromise, and of course the full/global can be switched to full/install with one env variable.

**Comment by viceice** [comment]
- related to #1237
