### ISSUE TITLE
Docker images are not being published to docker hub

### ISSUE THREAD

**Issue by rzuckerm** [renovatebot/docker-renovate-full#1826]
I'm not sure if this is the right place to log this issue or not, but renovate is currently at [35.117.1](https://www.npmjs.com/package/renovate), but no new docker image has been posted since [35.115.2](https://hub.docker.com/layers/renovate/renovate/35.115.2/images/sha256-ee90267dfac7643f39d1e02c1269bb0d5b221385af16a8ef0768d4218bb9bab2?context=explore). Is this expected? If so, how often are docker images posted?

**Comment by viceice** [comment]
already resolved, renovate was stuck
