### ISSUE TITLE
Python not installed in v36 image

### ISSUE THREAD

**Issue by chopeen** [renovatebot/docker-renovate-full#1949]
I am testing the `renovate/renovate:36.1.8 ` image. I am building a my own Renovate image with custom certificates. This worked for `v35`, but started failing for `v36`:

```
INFO[0062] Running: [/bin/bash -c pip config set global.cert /etc/ssl/certs/ca-certificates.crt] 
/bin/bash: pip: command not found
```

`pip` is not available, because `python` is no longer installed under `/opt/containerbase/tools/python`.

I can see the images differ significantly in size:

```
REPOSITORY         TAG     IMAGE ID       CREATED             SIZE
renovate/renovate  36.1.8  c0d1ca01275a   About an hour ago   1.13GB
renovate/renovate  35.158  bf290d487c3b   3 days ago          3.91GB
```

Is the `full` image no longer available?

**Comment by chopeen** [comment]
You need to use images with suffix `-full`, e.g. `docker pull renovate/renovate:36.1-full`.

See https://github.com/renovatebot/docker-renovate-full/pull/1919.

**Comment by viceice** [comment]
- https://docs.renovatebot.com/release-notes-for-major-versions/
