### ISSUE TITLE
Reuse layers from version to version

### ISSUE THREAD

**Issue by zeldigas** [renovatebot/docker-renovate-full#329]
Every version of renovate docker image is built from scratch that leads to the fact that when I update version, I need to download all image, even though only renovate itself is changed.

It'd be great to review current build and consider utilizing docker build cache (and `--cache-from` flag for cases when previous build was done on separate build agent).

**Comment by viceice** [comment]
Currently this image is build from the renovate slim docker image and it's using cache.

It would need a major refactor to do what you like.

@rarkins do you think we should build this image from buildpack and copy the slim image parts to here? Slowdown for builds should be less that a minute.

**Comment by rarkins** [comment]
@viceice yes, that sounds good

**Comment by zeldigas** [comment]
I'd say overall it might be even faster because you don't have to install all that long list of tools in this case.

Looking forward for updates on this.

**Comment by viceice** [comment]
Needs to be deferred at least to next week, as I'm currently away. 🚴😉

**Comment by viceice** [comment]
I'm also happy to accept a community pr. 🤗

**Comment by zeldigas** [comment]
I can take a look into Dockerfile change. Do I get it right that `Dockerfile` located in repo root in `main` branch is used?

**Comment by viceice** [comment]
Yes, check the readme link to the slim image for parts need to be copied here.

**Comment by zeldigas** [comment]
Just to confirm that it works MUCH better now from pull perspecitve: 
```
# 24.119 is pulled locally
$ docker pull renovate/renovate:25.1
25.1: Pulling from renovate/renovate
a70d879fa598: Already exists
c4394a92d1f8: Already exists
10e6159c56c0: Already exists
80a0cc4e9247: Already exists
e69b64195d83: Already exists
add118b39992: Already exists
a748eb1eb138: Already exists
a480b43f9b41: Already exists
caa06f78aa78: Already exists
3a1dfbdcd44f: Already exists
9436ebb775fb: Already exists
c72df85898e5: Already exists
bed8e0f6c64d: Already exists
d0ca41a52b26: Already exists
96287262f323: Already exists
e85e49a828b5: Already exists
fa0e33218604: Already exists
c718f0db9ac0: Already exists
016798e8f55f: Already exists
52fea6e660ec: Already exists
f529b81ef3cf: Already exists
50ee45b201bc: Already exists
6fe176f1d063: Already exists
415e7836a77f: Already exists
7398d141f8ef: Already exists
257986aed662: Already exists
9b7bc04654af: Already exists
85896fed9cac: Already exists
647b89cbd75a: Already exists
8b4ad0f9c353: Pull complete
abb4b8d79224: Pull complete
79f972bb063d: Pull complete
7ab24d70b20b: Pull complete
4af821c37de4: Pull complete
9c949608904c: Pull complete
Digest: sha256:e58d539e69a40d063ab4ff70ab07154cc8c890a05e77a6a47b9ca16c81699439
```
