### ISSUE TITLE
Current docker image ships a broken poetry installation

### ISSUE THREAD

**Issue by languitar** [renovatebot/docker-renovate-full#366]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v28.20.0

### Describe the bug

Recent Docker images contain a version of CacheControl inside the venv containing poetry that renders poetry unusable in some cases. The respective upstream bugs in poetry and CacheControl are https://github.com/python-poetry/poetry/issues/4688 and https://github.com/ionrock/cachecontrol/issues/263.

To make poetry usable again in all cases, a temporary workaround inside the docker image of renovate would be needed that downgrades CacheControl inside the poetry venv as proposed in the first issue.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
I have transferred and reopened it, although as I mentioned the fix might need to be e.g. in https://github.com/containerbase/buildpack/blob/main/src/usr/local/buildpack/tools/poetry.sh which is a different github org so can't be transferred to

**Comment by languitar** [comment]
> I have transferred and reopened it, although as I mentioned the fix might need to be e.g. in https://github.com/containerbase/buildpack/blob/main/src/usr/local/buildpack/tools/poetry.sh which is a different github org so can't be transferred to

I'm not sure how far this should traverse the dependency tree. #367 would solve this at least for the renovate docker image.

**Comment by viceice** [comment]
this is now fixed by composer update #368, as composer is before poetry, so it invalidates cache.

**Comment by viceice** [comment]
fixed versions: `28.20.1, 28.20.2, 28.21.0, 28.21.1, 28.21.2, 28.21.3, 28.21.4, 28.21.5, 28.21.6, 28.21.7`
