### ISSUE TITLE
New image with node v16 (LTS)

### ISSUE THREAD

**Issue by kalimerre** [renovatebot/docker-renovate-full#374]
Hello,

Node v16 had been released in the LTS mode (https://nodejs.org/en/blog/release/v16.13.0/). It also bundle npm v8.X in it which offers a package-lock v2.

Do you know when Renovate will offer new images with that new LTS version and therefore the new npm version ? 
I assume it'll be in a new major version of Renovate to not break existing projects on the current version right ?

Thanks !

**Comment by rarkins** [comment]
At the moment it's looking like weeks to months before we default the pre-built Renovate images to use Node 16. In the meantime you'd need to build your own custom image. e.g. https://github.com/renovatebot/docker-renovate-full/blob/main/Dockerfile

**Comment by viceice** [comment]
this is blocked by:

- https://github.com/renovatebot/renovate/issues/12177
- https://github.com/renovatebot/renovate/pull/12244

**Comment by Shegox** [comment]
As I just found this out today, there is a new self-hosted option [`"binarySource": "install"`](https://docs.renovatebot.com/self-hosted-configuration/#binarysource), which dynamically installs the npm version depending on the [engine field in the package.json](https://docs.renovatebot.com/node/#configuring-which-version-of-npm-renovate-uses) without using a sidecar container and allows to use lockFileVersion1 and lockFileVersion2 for different repositories.

**Comment by rarkins** [comment]
@Shegox yes, you're right. We'd be happy to hear feedback about whether it works flawlessly for you, because we plan to make it the default option for our images once we're confident we found and fixed any bugs or important edge cases

**Comment by Shegox** [comment]
@rarkins I just enabled it, but if any problems do come up I will make sure to open a proper bug report. From the first runs it looks like a really cool and good working feature! Thanks a lot for your and everyones awesome work on renovate!

**Comment by Ugoku** [comment]
> this is blocked by:
> 
> * [Test/validate node 16 for Renovate runtime renovate#12177](https://github.com/renovatebot/renovate/issues/12177)
> * [ci: add node v16 tests renovate#12244](https://github.com/renovatebot/renovate/pull/12244)

It seems there is nothing blocking this anymore. Any status update?

**Comment by scinos** [comment]
FWIW, renovate 32.72-slim has node 16:

```
$ docker run --rm -ti --entrypoint /bin/bash renovate/renovate:32.72-slim -c 'node --version'
v16.15.1
```

**Comment by rarkins** [comment]
Let's do a major release of Renovate next week so we can coincide this to be more polite to those who might be surprised that the node version changes in the full image

**Comment by dmosen** [comment]
@rarkins We are also affected by this issue. As we are using OpenShift and we are having some trouble getting `binarySource=install` or `binarySource=docker` to work, a renovate full image with preinstalled node 16 would be helpful for us.

**Comment by scinos** [comment]
Is there something I can do to help this happening? 

I see there is a pending Node 16 update in the Dependency Dashboard, but I can't click on it to force a PR creation.

**Comment by viceice** [comment]
Nope, still blocked by missing renovate feature

**Comment by viceice** [comment]
no, it's because we break a lot existing users who need an older npm version.

so we wait for dynamic node install to support that. after we'll update node on this image.

**Comment by dmosen** [comment]
We finally got `binarySource=install` working in our OpenShift installation:

To fix this problem we needed to add `BUILDPACK=1` explicitly to the container's environment variables. (We did so by adding the variable to the [kubernetes manifest](https://docs.renovatebot.com/examples/self-hosting/#kubernetes).)

**Explanation**

If you use Renovate on OpenShift the Renovate process is started by a dynamically generated user using `/bin/sh` instead of `/bin/bash`. In this case the environment variable `BUILDPACK` is not being set. This results in Renovate refusing to apply `binarySource=install`. If this is the case the Renovate logs contain the following entry:
`binarySource=install is only compatible with images derived from containerbase/buildpack`

**Comment by rarkins** [comment]
Thanks for the info. Would this be something we could fix automatically if `/bin/sh` wraps `/bin/bash`?

**Comment by dmosen** [comment]
I think this should work. Starting `/bin/bash` inside `/bin/sh` also worked for us.

**Comment by viceice** [comment]
Can we simply add a small bash script as `/bin/sh` ?

```sh
#!/bin/bash

if [[ -f "$BASH_ENV" && -z "${BUILDPACK+x}" ]]; then
  . $BASH_ENV
fi

exec dumb-init -- "$@"
```

This will help to autoload our env in any case. So also jenkins pipelines work, as they use `docker exec` to execute commands.

Can someone evaluate if this works and then open an issue on https://github.com/containerbase/buildpack to autocreate this on `install-buildpack`

**Comment by scinos** [comment]
`binarySource=install` won't affect which Node version is used, only which `npm` version, right?

**Comment by viceice** [comment]
yes, we will enable `install` mode soon

**Comment by viceice** [comment]
will be done tomorrow
