### ISSUE TITLE
Repository is not found: version 28.16.0 is working, next release 28.17.0 introduces error

### ISSUE THREAD

**Issue by exploiz65** [renovatebot/docker-renovate-full#380]
Hello renovate developer,

We setup renovatebot for our organization its working fine but we  recognized than when using latest there is this error he is not able to find the repository in github but it exist. We recognized version 28.16.0 is working, next release 28.17.0 introduces this error:

--> docker run --rm -u0 -v /home/user/co/ansible-github/config.js:/usr/src/app/config.js -e LOG_LEVEL=info  **********/renovate/renovate:latest
(node:8) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
 INFO: Repository started (repository=test/abc)
       "renovateVersion": "28.21.5"
ERROR: Repository is not found (repository=test/abc)
 INFO: Repository finished (repository=test/abc)
       "durationMs": 79
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "aVjScpqhr",
           "repository": "test/abc",
           "msg": "Repository is not found"
         }
       ]

with this config:

module.exports = {
  "endpoint": "*************************",
  "token": "**********************************************",
  "platform": "github",
  "onboardingConfig": {"extends": ["config:base"]},
  "repositories": ["test/abc"],
  "fetchReleaseNotes": false
};

**Comment by rarkins** [comment]
Upgrade to latest version and retry
