### ISSUE TITLE
Use `binarySource=install`

### ISSUE THREAD

**Issue by viceice** [renovatebot/docker-renovate-full#406]
We should switch default `binarySource` to install mode.

- https://github.com/renovatebot/renovate/issues/14531

**Comment by rarkins** [comment]
We might also need an image which sits between "slim" and "full", which contains only the languages/managers which can't be installed with binarySource=install.

i.e. for those comfortable with binarySource=install and want to take advantage of a smaller prebuilt renovate/renovate image.

**Comment by rarkins** [comment]
I think we should go ahead with this now, including updating to node and npm latest versions

**Comment by rarkins** [comment]
Question is, should we set `RENOVATE_BINARY_SOURCE=install` in the env of this container, or should we change its default in Renovate itself? I think the way it's written, it only does install if it detects it's in a containerbase image, which is likely only the ones we distribute anyway.

**Comment by viceice** [comment]
Makes sense to enable it in renovate as default.

It would make no big difference for now for the full image, as the already installed versions shouldn't be reinstalled.

**Comment by viceice** [comment]
@rarkins We need to document that this requires to run renovate with root group id, otherwise we're missing write permissions on install folders.

**Comment by rarkins** [comment]
Can we make it so that you need to run with EITHER uid=1000 OR guid=0 ?

**Comment by viceice** [comment]
no, `1000:1000` won't work, as that would require more system folders to be owned by 1000. Don't like that idea.

**Comment by rarkins** [comment]
I guess we should find or create some documentation reminding users why root group is not the same as root user, and just stick to our decision?

**Comment by viceice** [comment]
Sounds good

**Comment by rarkins** [comment]
Does our containerbase allow group id to be configurable, if someone is building on their own from scratch and really wants a different group?

**Comment by viceice** [comment]
No, currently we create the user and group with same name and id. And then we make root group the primary group.

**Comment by viceice** [comment]
this is now done since v34
