### ISSUE TITLE
Frequent digest updates

### ISSUE THREAD

**Issue by varac** [renovatebot/docker-renovate-full#420]
We get frequent merge requests to update the image digest of `renovate/renovate`, which gets auto-closed but still generate noise:

![image](https://user-images.githubusercontent.com/488213/165686149-6c2e4039-2447-4a65-92f6-a169692286e7.png)

i.e. tonight, for `32.32.2`:

```
  image:
-    renovate/renovate:32.32.2@sha256:e0d4672e2a696b515b88b1a3faa22fed19cdbdf78959bb6873e1a02d636994b4
+    renovate/renovate:32.32.2@sha256:a63eada8ab931ad9741519d019850ebc5df64640c545243fe37d381134db65c6
```

hub.docker.com shows indeed the image tag `32.32.2` got updated 19h ago:

![image](https://user-images.githubusercontent.com/488213/165686591-752cc72f-ac56-4b48-84ae-23778b63f3e3.png)

Why are existing image tags updated in place ? Imo they shouldn't, as pointed out in From https://docs.renovatebot.com/docker/#digest-pinning itself:

> What you may not know is that Docker's tags are not immutable versions, even if they look like a version. e.g. you probably expect myimage:1 and myimage:1.2 to change over time, but you might incorrectly assume that myimage:1.2.0 never changes. Although it probably shouldn't, the reality is that any Docker image tag can change content, and potentially break.

**Comment by rarkins** [comment]
You can disable digest updates for Renovate if you wish. We cannot promise to never update a tag, because we intentionally want to do that if there's an update to the underlying base image or other important third party library.
