### ISSUE TITLE
Tag 22 missing in docker hub

### ISSUE THREAD

**Issue by frbuceta** [renovatebot/docker-renovate-full#52]
Hello, I wanted to update my image to version 22 with docker and I could not because the tag does not exist

**Comment by viceice** [comment]
`22-slim` is there, full image is in preparation

**Comment by frbuceta** [comment]
Perfect thanks for the info

**Comment by viceice** [comment]
Merged, should be available in ~10min

**Comment by frbuceta** [comment]
Thanks
