### ISSUE TITLE
python "packaging" package is missing

### ISSUE THREAD

**Issue by caphrim007** [renovatebot/docker-renovate-full#56]
**What Renovate type are you using?**

self-hosted, bitbucket, renovate version 22.17.2

**Describe the bug**

When updating a requirements file with hashes in python, an error about missing `packaging` package is raised

```
DEBUG: Failed to update requirements/constraints.txt file (repository=myorg/vss-ops-utils, branch=renovate/identify-1.x)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "hashin identify==1.4.27 -r requirements/constraints.txt",
         "stdout": "",
         "stderr": "Traceback (most recent call last):\n  File \"/usr/local/python/3.8.5/bin/hashin\", line 5, in <module>\n    from
 hashin import main\n  File \"/usr/local/python/3.8.5/lib/python3.8/site-packages/hashin.py\", line 21, in <module>\n    from
 packaging.requirements import Requirement\nModuleNotFoundError: No module named 'packaging'\n",
         "message": "Command failed: hashin identify==1.4.27 -r requirements/constraints.txt\nTraceback (most recent call 
last):\n  File \"/usr/local/python/3.8.5/bin/hashin\", line 5, in <module>\n    from hashin import main\n  File 
\"/usr/local/python/3.8.5/lib/python3.8/site-packages/hashin.py\", line 21, in <module>\n    from packaging.requirements 
import Requirement\nModuleNotFoundError: No module named 'packaging'\n",
         "stack": "Error: Command failed: hashin identify==1.4.27 -r requirements/constraints.txt\nTraceback (most recent call 
last):\n  File \"/usr/local/python/3.8.5/bin/hashin\", line 5, in <module>\n    from hashin import main\n  File 
\"/usr/local/python/3.8.5/lib/python3.8/site-packages/hashin.py\", line 21, in <module>\n    from packaging.requirements 
import Requirement\nModuleNotFoundError: No module named 'packaging'\n\n    at ChildProcess.exithandler 
(child_process.js:303:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit 
(domain.js:483:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit 
(internal/child_process.js:286:5)"
       }
```

is it possible that the python image used by renovate failed to install this?

**Relevant debug logs**

**To Reproduce**

I think this should be reproducible in any repository that uses hashes in the python requirements file. 

**Additional context**

**Comment by caphrim007** [comment]
I looked at the other images and 22.17.2 is the first time this problem showed up (looked at the other images from 22.16.2 through to 22.17.2)

**Comment by rarkins** [comment]
@viceice I don't see anything obvious in [the commits](https://github.com/renovatebot/docker-renovate-full/commits/master)

**Comment by rarkins** [comment]
From the build for 22.17.2:

```
2020-08-14T13:03:35.3756446Z #17 [stage-1 13/18] RUN install-pip hashin 0.15.0
2020-08-14T13:03:35.5253729Z #17 0.115 Installing pip hashin v0.15.0
2020-08-14T13:03:35.8010411Z #17 0.457 Collecting hashin==0.15.0
2020-08-14T13:03:35.8011650Z #17 0.489   Downloading hashin-0.15.0-py2.py3-none-any.whl (16 kB)
2020-08-14T13:03:35.8012500Z #17 0.505 Requirement already satisfied: packaging in /root/.local/lib/python3.8/site-packages (from hashin==0.15.0) (20.4)
```

Seemingly same log from 22.17.1:

```
2020-08-14T09:04:50.0706871Z #16 [stage-1 13/18] RUN install-pip hashin 0.15.0
2020-08-14T09:04:50.2158061Z #16 0.121 Installing pip hashin v0.15.0
2020-08-14T09:04:50.4972842Z #16 0.517 Collecting hashin==0.15.0
2020-08-14T09:04:50.6052279Z #16 0.562   Downloading hashin-0.15.0-py2.py3-none-any.whl (16 kB)
2020-08-14T09:04:50.6053007Z #16 0.582 Requirement already satisfied: packaging in /root/.local/lib/python3.8/site-packages (from hashin==0.15.0) (20.4)
```

**Comment by caphrim007** [comment]
ahh, that's interesting. Does renovate need to run as the root user?

**Comment by caphrim007** [comment]
in 22.17.1, the pip output from freeze shows a different set of packages than from what 22.17.2 shows. Below is 22.17.1

```
ubuntu@7eb9924f6c7e:/usr/src/app$ /usr/local/python/3.8.5/bin/pip freeze
appdirs==1.4.4
certifi==2020.6.20
distlib==0.3.1
filelock==3.0.12
hashin==0.15.0
packaging==20.4
pip-api==0.0.14
pipenv==2020.8.13
pyparsing==2.4.7
six==1.15.0
virtualenv==20.0.30
virtualenv-clone==0.5.4
ubuntu@7eb9924f6c7e:/usr/src/app$
```

**Comment by caphrim007** [comment]
note, that I run renovate as a non-root user in my env which may be partially responsible for why this is happening

**Comment by caphrim007** [comment]
(but in my defense, it worked in the past and it didn't seem like root would be necessary for the work being done by the bot)

**Comment by viceice** [comment]
By default renovate runs as user ubuntu (1000).

There is something wrong with install pip packages, as we install it globally and it seems to reference packages from private root folder.
Maybe a change in pip?

**Comment by caphrim007** [comment]
i read that there is an upcoming change in the pip default package version resolver, but that's not supposed to be released until October timeframe. That's the only pip thing I'm familiar with because it's going to affect my own packages.

**Comment by rarkins** [comment]
As a general rule - if you change the image we build including user then all bets are off. It's too easy for things that don't seem relevant to be causing problems. Let's ensure this fails the same way as Ubuntu user and reproduce only on the pristine image.

**Comment by caphrim007** [comment]
i'm not changing the image per-se, i'm just specifying a different run-as user within kubernetes for it.

The examples I gave above though are running it normally; with whatever configuration is provided by renovate itself. I can confirm I get the same behavior when I remove the user I specify in the cronjob.

**Comment by caphrim007** [comment]
@rarkins @viceice the error disappeared in 22.17.4. Feels like it was a bad build. I'll look at the other images, and close this issue in the meantime.
